//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Works = new HashSet<Work>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> TeamLeaderId { get; set; }
        public int Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TeamMember TeamMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work> Works { get; set; }
    }
}
