//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetEntry
    {
        public int CategoryId { get; set; }
        public int ProjectId { get; set; }
        public int TeamMemberId { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int Id { get; set; }
        public Nullable<int> Overtime { get; set; }
        public double Time { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Work Work { get; set; }
    }
}
