//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {
            this.TimeSheetEntries = new HashSet<TimeSheetEntry>();
        }
    
        public int TeamMemberId { get; set; }
        public int ProjectId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TeamMember TeamMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSheetEntry> TimeSheetEntries { get; set; }
    }
}
